'📌 area: components':
  - any: ['packages/components/**/*']

'📌 area: shadcn':
  - any: ['packages/shadcn/**/*']

'📌 area: web':
  - any: ['apps/spren-ui/**/*']

'📌 area: zag-angular':
  - any: ['packages/zag-angular/**/*']

'📚 documentation':
  - any: ['**/*.md']

'📌 area: ci':
  - any: ['.github/**/*']
