# Adapted from Analog & create-t3-app.
name: CI

on:
  pull_request:
    branches: ['*']
  merge_group:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    permissions:
      actions: read
      contents: read
      # Required by wagoid/commitlint-github-action
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
        with:
          # Required by wagoid/commitlint-github-action
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true
          helpURL: https://github.com/saulmoro/spren-ui/blob/main/.github/CONTRIBUTING.md#-commit-message-guidelines

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm affected:lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Validate
        run: pnpm exec prettier --check .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: pnpm affected:build

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Test
        run: pnpm affected:test

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Install Cypress
        run: npx cypress install
      - name: End-to-end test
        run: pnpm affected:e2e
