# Adapted from Analog & create-t3-app.
name: CI

on:
  pull_request:
    branches: ['*']
  merge_group:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    permissions:
      actions: read
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true
          helpURL: https://github.com/spren-ui/spren-ui/blob/main/.github/CONTRIBUTING.md#-commit-message-guidelines

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/composite-actions/install
      - name: Lint
        run: pnpm affected:lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/composite-actions/install
      - name: Validate
        run: pnpm prettier --check .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/composite-actions/install
      - name: Build
        run: pnpm affected:build

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/composite-actions/install
      - name: Test
        run: pnpm affected:test

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/composite-actions/install
      - name: Install Cypress
        run: npx cypress install
      - name: End-to-end test
        run: pnpm affected:e2e
