# Adapted from create-t3-app.
name: Release - Beta

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  prerelease:
    if: |
      github.repository_owner == 'spren-ui' &&
      contains(github.event.pull_request.labels.*.name, '🚀 autorelease')
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/composite-actions/install

      - name: Modify package.json version
        run: node .github/version-script-beta.mjs

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > packages/components/.npmrc

      - name: Publish Beta to NPM
        run: pnpm pub:beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/components

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v2
        with:
          name: npm-package-spren-ui-components@${{ steps.package-version.outputs.current-version }}-pr-${{ github.event.number }} # encode the PR number into the artifact name
          path: dist/packages/components/
